using UXDivers.Grial;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERM_HSYT {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DemoAppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DemoAppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ERM_HSYT.DemoAppResources", typeof(DemoAppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitleThemesPreview {
            get {
                return ResourceManager.GetString("PageTitleThemesPreview", resourceCulture);
            }
        }
        
        internal static string StringApply {
            get {
                return ResourceManager.GetString("StringApply", resourceCulture);
            }
        }
        
        internal static string ScreenCount {
            get {
                return ResourceManager.GetString("ScreenCount", resourceCulture);
            }
        }
        
        internal static string MainMenuWhatsNew {
            get {
                return ResourceManager.GetString("MainMenuWhatsNew", resourceCulture);
            }
        }
        
        internal static string MainMenuControlsAndFeatures {
            get {
                return ResourceManager.GetString("MainMenuControlsAndFeatures", resourceCulture);
            }
        }
        
        internal static string MainMenuCustomControls {
            get {
                return ResourceManager.GetString("MainMenuCustomControls", resourceCulture);
            }
        }
        
        internal static string MainMenuDashboard {
            get {
                return ResourceManager.GetString("MainMenuDashboard", resourceCulture);
            }
        }
        
        internal static string MainMenuIcons {
            get {
                return ResourceManager.GetString("MainMenuIcons", resourceCulture);
            }
        }
        
        internal static string MainMenuGrialThemes {
            get {
                return ResourceManager.GetString("MainMenuGrialThemes", resourceCulture);
            }
        }
        
        internal static string MainMenuAbout {
            get {
                return ResourceManager.GetString("MainMenuAbout", resourceCulture);
            }
        }
        
        internal static string DemoAppPageTitleAbout {
            get {
                return ResourceManager.GetString("DemoAppPageTitleAbout", resourceCulture);
            }
        }
        
        internal static string StringGetGrial {
            get {
                return ResourceManager.GetString("StringGetGrial", resourceCulture);
            }
        }
        
        internal static string StringGetGrialNow {
            get {
                return ResourceManager.GetString("StringGetGrialNow", resourceCulture);
            }
        }
        
        internal static string ButtonBrowseOurSamples {
            get {
                return ResourceManager.GetString("ButtonBrowseOurSamples", resourceCulture);
            }
        }
        
        internal static string ButtonSeeOurWalkThrough {
            get {
                return ResourceManager.GetString("ButtonSeeOurWalkThrough", resourceCulture);
            }
        }
        
        internal static string FlowDescriptionMovies {
            get {
                return ResourceManager.GetString("FlowDescriptionMovies", resourceCulture);
            }
        }
        
        internal static string FlowDescriptionEcommerce {
            get {
                return ResourceManager.GetString("FlowDescriptionEcommerce", resourceCulture);
            }
        }
        
        internal static string FlowDescriptionTasks {
            get {
                return ResourceManager.GetString("FlowDescriptionTasks", resourceCulture);
            }
        }
        
        internal static string FlowDescriptionMessages {
            get {
                return ResourceManager.GetString("FlowDescriptionMessages", resourceCulture);
            }
        }
        
        internal static string DocumentTimelinePageDescription {
            get {
                return ResourceManager.GetString("DocumentTimelinePageDescription", resourceCulture);
            }
        }
        
        internal static string TimelinePageDescription {
            get {
                return ResourceManager.GetString("TimelinePageDescription", resourceCulture);
            }
        }
        
        internal static string ProfilePageTimelinePageDescription {
            get {
                return ResourceManager.GetString("ProfilePageTimelinePageDescription", resourceCulture);
            }
        }
        
        internal static string SocialPageDescription {
            get {
                return ResourceManager.GetString("SocialPageDescription", resourceCulture);
            }
        }
        
        internal static string SocialVariantPageDescription {
            get {
                return ResourceManager.GetString("SocialVariantPageDescription", resourceCulture);
            }
        }
        
        internal static string SocialCardPageDescription {
            get {
                return ResourceManager.GetString("SocialCardPageDescription", resourceCulture);
            }
        }
        
        internal static string FullHeaderArticlePagePageDescription {
            get {
                return ResourceManager.GetString("FullHeaderArticlePagePageDescription", resourceCulture);
            }
        }
        
        internal static string ArticlesClassicViewPageDescription {
            get {
                return ResourceManager.GetString("ArticlesClassicViewPageDescription", resourceCulture);
            }
        }
        
        internal static string ArticlesColumnPageDescription {
            get {
                return ResourceManager.GetString("ArticlesColumnPageDescription", resourceCulture);
            }
        }
        
        internal static string ArticleDetailPageDescription {
            get {
                return ResourceManager.GetString("ArticleDetailPageDescription", resourceCulture);
            }
        }
        
        internal static string ArticlesListPageDescription {
            get {
                return ResourceManager.GetString("ArticlesListPageDescription", resourceCulture);
            }
        }
        
        internal static string ArticlesFeedPageDescription {
            get {
                return ResourceManager.GetString("ArticlesFeedPageDescription", resourceCulture);
            }
        }
        
        internal static string DashboardCarouselPageDescription {
            get {
                return ResourceManager.GetString("DashboardCarouselPageDescription", resourceCulture);
            }
        }
        
        internal static string NavigationCardsDescriptionListPageDescription {
            get {
                return ResourceManager.GetString("NavigationCardsDescriptionListPageDescription", resourceCulture);
            }
        }
        
        internal static string MoviesMainPageDescription {
            get {
                return ResourceManager.GetString("MoviesMainPageDescription", resourceCulture);
            }
        }
        
        internal static string MovieDetailPageDescription {
            get {
                return ResourceManager.GetString("MovieDetailPageDescription", resourceCulture);
            }
        }
        
        internal static string DashboardCardsPageDescription {
            get {
                return ResourceManager.GetString("DashboardCardsPageDescription", resourceCulture);
            }
        }
        
        internal static string DashboardMultipleTilesPageDescription {
            get {
                return ResourceManager.GetString("DashboardMultipleTilesPageDescription", resourceCulture);
            }
        }
        
        internal static string IconsDashboardPageDescription {
            get {
                return ResourceManager.GetString("IconsDashboardPageDescription", resourceCulture);
            }
        }
        
        internal static string FlatDashboardPageDescription {
            get {
                return ResourceManager.GetString("FlatDashboardPageDescription", resourceCulture);
            }
        }
        
        internal static string ImagesDashboardPageDescription {
            get {
                return ResourceManager.GetString("ImagesDashboardPageDescription", resourceCulture);
            }
        }
        
        internal static string NavigationCardsListPageDescription {
            get {
                return ResourceManager.GetString("NavigationCardsListPageDescription", resourceCulture);
            }
        }
        
        internal static string EmptyStatePageDescription {
            get {
                return ResourceManager.GetString("EmptyStatePageDescription", resourceCulture);
            }
        }
        
        internal static string NotificationsPageDescription {
            get {
                return ResourceManager.GetString("NotificationsPageDescription", resourceCulture);
            }
        }
        
        internal static string NavigationFlatListPageDescription {
            get {
                return ResourceManager.GetString("NavigationFlatListPageDescription", resourceCulture);
            }
        }
        
        internal static string NavigationListWithImagesPageDescription {
            get {
                return ResourceManager.GetString("NavigationListWithImagesPageDescription", resourceCulture);
            }
        }
        
        internal static string NavigationListWithIconsPageDescription {
            get {
                return ResourceManager.GetString("NavigationListWithIconsPageDescription", resourceCulture);
            }
        }
        
        internal static string TabbedLoginPageDescription {
            get {
                return ResourceManager.GetString("TabbedLoginPageDescription", resourceCulture);
            }
        }
        
        internal static string SimpleSignUpPageDescription {
            get {
                return ResourceManager.GetString("SimpleSignUpPageDescription", resourceCulture);
            }
        }
        
        internal static string SimpleLoginPageDescription {
            get {
                return ResourceManager.GetString("SimpleLoginPageDescription", resourceCulture);
            }
        }
        
        internal static string LoginPageDescription {
            get {
                return ResourceManager.GetString("LoginPageDescription", resourceCulture);
            }
        }
        
        internal static string SignUpPageDescription {
            get {
                return ResourceManager.GetString("SignUpPageDescription", resourceCulture);
            }
        }
        
        internal static string PasswordRecoveryPageDescription {
            get {
                return ResourceManager.GetString("PasswordRecoveryPageDescription", resourceCulture);
            }
        }
        
        internal static string ProductImageFullScreenPageDescription {
            get {
                return ResourceManager.GetString("ProductImageFullScreenPageDescription", resourceCulture);
            }
        }
        
        internal static string ProductsCatalogPageDescription {
            get {
                return ResourceManager.GetString("ProductsCatalogPageDescription", resourceCulture);
            }
        }
        
        internal static string ProductOrderPageDescription {
            get {
                return ResourceManager.GetString("ProductOrderPageDescription", resourceCulture);
            }
        }
        
        internal static string ProductsGridPageDescription {
            get {
                return ResourceManager.GetString("ProductsGridPageDescription", resourceCulture);
            }
        }
        
        internal static string ProductsGridVariantPageDescription {
            get {
                return ResourceManager.GetString("ProductsGridVariantPageDescription", resourceCulture);
            }
        }
        
        internal static string ProductItemViewPageDescription {
            get {
                return ResourceManager.GetString("ProductItemViewPageDescription", resourceCulture);
            }
        }
        
        internal static string ProductsCarouselPageDescription {
            get {
                return ResourceManager.GetString("ProductsCarouselPageDescription", resourceCulture);
            }
        }
        
        internal static string WalkthroughPageDescription {
            get {
                return ResourceManager.GetString("WalkthroughPageDescription", resourceCulture);
            }
        }
        
        internal static string WalkthroughFlatPageDescription {
            get {
                return ResourceManager.GetString("WalkthroughFlatPageDescription", resourceCulture);
            }
        }
        
        internal static string WalkthroughVariantPageDescription {
            get {
                return ResourceManager.GetString("WalkthroughVariantPageDescription", resourceCulture);
            }
        }
        
        internal static string ChatTimelinePageDescription {
            get {
                return ResourceManager.GetString("ChatTimelinePageDescription", resourceCulture);
            }
        }
        
        internal static string RecentChatListPageDescription {
            get {
                return ResourceManager.GetString("RecentChatListPageDescription", resourceCulture);
            }
        }
        
        internal static string MessagesListPageDescription {
            get {
                return ResourceManager.GetString("MessagesListPageDescription", resourceCulture);
            }
        }
        
        internal static string ChatMessagesListPageDescription {
            get {
                return ResourceManager.GetString("ChatMessagesListPageDescription", resourceCulture);
            }
        }
        
        internal static string TabControlCustomSamplePageDescription {
            get {
                return ResourceManager.GetString("TabControlCustomSamplePageDescription", resourceCulture);
            }
        }
        
        internal static string TabControlAndroidSamplePageDescription {
            get {
                return ResourceManager.GetString("TabControlAndroidSamplePageDescription", resourceCulture);
            }
        }
        
        internal static string TabControliOSSamplePageDescription {
            get {
                return ResourceManager.GetString("TabControliOSSamplePageDescription", resourceCulture);
            }
        }
        
        internal static string TabControlBottomPlacementSamplePageDescription {
            get {
                return ResourceManager.GetString("TabControlBottomPlacementSamplePageDescription", resourceCulture);
            }
        }
        
        internal static string TabPageDescription {
            get {
                return ResourceManager.GetString("TabPageDescription", resourceCulture);
            }
        }
        
        internal static string DemoSettingsPageDescription {
            get {
                return ResourceManager.GetString("DemoSettingsPageDescription", resourceCulture);
            }
        }
        
        internal static string GenericAboutPageDescription {
            get {
                return ResourceManager.GetString("GenericAboutPageDescription", resourceCulture);
            }
        }
        
        internal static string RichAboutPageDescription {
            get {
                return ResourceManager.GetString("RichAboutPageDescription", resourceCulture);
            }
        }
        
        internal static string CustomSettingsPageDescription {
            get {
                return ResourceManager.GetString("CustomSettingsPageDescription", resourceCulture);
            }
        }
        
        internal static string CustomActivityIndicatorPageDescription {
            get {
                return ResourceManager.GetString("CustomActivityIndicatorPageDescription", resourceCulture);
            }
        }
        
        internal static string ResponsiveHelpersPageDescription {
            get {
                return ResourceManager.GetString("ResponsiveHelpersPageDescription", resourceCulture);
            }
        }
        
        internal static string IconsPageDescription {
            get {
                return ResourceManager.GetString("IconsPageDescription", resourceCulture);
            }
        }
        
        internal static string ThemeOverviewPageDescription {
            get {
                return ResourceManager.GetString("ThemeOverviewPageDescription", resourceCulture);
            }
        }
        
        internal static string CustomRenderersPageDescription {
            get {
                return ResourceManager.GetString("CustomRenderersPageDescription", resourceCulture);
            }
        }
        
        internal static string SettingsPageDescription {
            get {
                return ResourceManager.GetString("SettingsPageDescription", resourceCulture);
            }
        }
        
        internal static string PerformanceDashboardMainPageDescription {
            get {
                return ResourceManager.GetString("PerformanceDashboardMainPageDescription", resourceCulture);
            }
        }
        
        internal static string EmployeePerformanceDashboardPageDescription {
            get {
                return ResourceManager.GetString("EmployeePerformanceDashboardPageDescription", resourceCulture);
            }
        }
        
        internal static string EmployeeProfileDashboardPageDescription {
            get {
                return ResourceManager.GetString("EmployeeProfileDashboardPageDescription", resourceCulture);
            }
        }
        
        internal static string AddContactPageDescription {
            get {
                return ResourceManager.GetString("AddContactPageDescription", resourceCulture);
            }
        }
        
        internal static string ContactSimpleDetailPageDescription {
            get {
                return ResourceManager.GetString("ContactSimpleDetailPageDescription", resourceCulture);
            }
        }
        
        internal static string ContactDetailPageDescription {
            get {
                return ResourceManager.GetString("ContactDetailPageDescription", resourceCulture);
            }
        }
        
        internal static string ChatMessagesPageDescription {
            get {
                return ResourceManager.GetString("ChatMessagesPageDescription", resourceCulture);
            }
        }
        
        internal static string ChatMainPageDescription {
            get {
                return ResourceManager.GetString("ChatMainPageDescription", resourceCulture);
            }
        }
        
        internal static string CardArticlePageDescription {
            get {
                return ResourceManager.GetString("CardArticlePageDescription", resourceCulture);
            }
        }
        
        internal static string ArticlesBrowserPageDescription {
            get {
                return ResourceManager.GetString("ArticlesBrowserPageDescription", resourceCulture);
            }
        }
        
        internal static string FeaturedMoviesPageDescription {
            get {
                return ResourceManager.GetString("FeaturedMoviesPageDescription", resourceCulture);
            }
        }
        
        internal static string CurvedHeaderArticlePageDescription {
            get {
                return ResourceManager.GetString("CurvedHeaderArticlePageDescription", resourceCulture);
            }
        }
        
        internal static string OrganizationFormPageDescription {
            get {
                return ResourceManager.GetString("OrganizationFormPageDescription", resourceCulture);
            }
        }
        
        internal static string FullBackgroundLoginPageDescription {
            get {
                return ResourceManager.GetString("FullBackgroundLoginPageDescription", resourceCulture);
            }
        }
        
        internal static string FullBackgroundSignupPageDescription {
            get {
                return ResourceManager.GetString("FullBackgroundSignupPageDescription", resourceCulture);
            }
        }
        
        internal static string EmployeeFormPageDescription {
            get {
                return ResourceManager.GetString("EmployeeFormPageDescription", resourceCulture);
            }
        }
        
        internal static string EcommerceMainPageDescription {
            get {
                return ResourceManager.GetString("EcommerceMainPageDescription", resourceCulture);
            }
        }
        
        internal static string ProductDetailPageDescription {
            get {
                return ResourceManager.GetString("ProductDetailPageDescription", resourceCulture);
            }
        }
        
        internal static string OrderConfirmationPageDescription {
            get {
                return ResourceManager.GetString("OrderConfirmationPageDescription", resourceCulture);
            }
        }
        
        internal static string CheckoutPageDescription {
            get {
                return ResourceManager.GetString("CheckoutPageDescription", resourceCulture);
            }
        }
        
        internal static string VideoCarouselHighlightsPageDescription {
            get {
                return ResourceManager.GetString("VideoCarouselHighlightsPageDescription", resourceCulture);
            }
        }
        
        internal static string WalkthroughGradientPageDescription {
            get {
                return ResourceManager.GetString("WalkthroughGradientPageDescription", resourceCulture);
            }
        }
        
        internal static string WalkthroughImagePageDescription {
            get {
                return ResourceManager.GetString("WalkthroughImagePageDescription", resourceCulture);
            }
        }
        
        internal static string WalkthroughMinimalPageDescription {
            get {
                return ResourceManager.GetString("WalkthroughMinimalPageDescription", resourceCulture);
            }
        }
        
        internal static string PopupsPageDescription {
            get {
                return ResourceManager.GetString("PopupsPageDescription", resourceCulture);
            }
        }
        
        internal static string ShippingDetailPageDescription {
            get {
                return ResourceManager.GetString("ShippingDetailPageDescription", resourceCulture);
            }
        }
        
        internal static string TaskBrowserPageDescription {
            get {
                return ResourceManager.GetString("TaskBrowserPageDescription", resourceCulture);
            }
        }
        
        internal static string TaskOverviewPageDescription {
            get {
                return ResourceManager.GetString("TaskOverviewPageDescription", resourceCulture);
            }
        }
        
        internal static string FeatureRtlInvite {
            get {
                return ResourceManager.GetString("FeatureRtlInvite", resourceCulture);
            }
        }
        
        internal static string FeatureI18nInvite {
            get {
                return ResourceManager.GetString("FeatureI18nInvite", resourceCulture);
            }
        }
        
        internal static string FeatureI18nTitle {
            get {
                return ResourceManager.GetString("FeatureI18nTitle", resourceCulture);
            }
        }
        
        internal static string FeatureI18nDescription {
            get {
                return ResourceManager.GetString("FeatureI18nDescription", resourceCulture);
            }
        }
        
        internal static string FeatureRTLTitle {
            get {
                return ResourceManager.GetString("FeatureRTLTitle", resourceCulture);
            }
        }
        
        internal static string FeatureRTLDescription {
            get {
                return ResourceManager.GetString("FeatureRTLDescription", resourceCulture);
            }
        }
        
        internal static string FeatureDataGridTitle {
            get {
                return ResourceManager.GetString("FeatureDataGridTitle", resourceCulture);
            }
        }
        
        internal static string FeatureDataGridDescription {
            get {
                return ResourceManager.GetString("FeatureDataGridDescription", resourceCulture);
            }
        }
        
        internal static string FeatureCardViewTitle {
            get {
                return ResourceManager.GetString("FeatureCardViewTitle", resourceCulture);
            }
        }
        
        internal static string FeatureCardViewDescription {
            get {
                return ResourceManager.GetString("FeatureCardViewDescription", resourceCulture);
            }
        }
        
        internal static string FeatureVideoPlayerTitle {
            get {
                return ResourceManager.GetString("FeatureVideoPlayerTitle", resourceCulture);
            }
        }
        
        internal static string FeatureVideoPlayerDescription {
            get {
                return ResourceManager.GetString("FeatureVideoPlayerDescription", resourceCulture);
            }
        }
        
        internal static string FeaturePopupsTitle {
            get {
                return ResourceManager.GetString("FeaturePopupsTitle", resourceCulture);
            }
        }
        
        internal static string FeaturePopupsDescription {
            get {
                return ResourceManager.GetString("FeaturePopupsDescription", resourceCulture);
            }
        }
        
        internal static string FeatureCarouselViewTitle {
            get {
                return ResourceManager.GetString("FeatureCarouselViewTitle", resourceCulture);
            }
        }
        
        internal static string FeatureCarouselViewDescription {
            get {
                return ResourceManager.GetString("FeatureCarouselViewDescription", resourceCulture);
            }
        }
        
        internal static string FeatureAnimationsViewTitle {
            get {
                return ResourceManager.GetString("FeatureAnimationsViewTitle", resourceCulture);
            }
        }
        
        internal static string FeatureAnimationsViewDescription {
            get {
                return ResourceManager.GetString("FeatureAnimationsViewDescription", resourceCulture);
            }
        }
        
        internal static string FeatureGradientsViewTitle {
            get {
                return ResourceManager.GetString("FeatureGradientsViewTitle", resourceCulture);
            }
        }
        
        internal static string FeatureGradientsViewDescription {
            get {
                return ResourceManager.GetString("FeatureGradientsViewDescription", resourceCulture);
            }
        }
        
        internal static string FeatureGrialNavbarViewTitle {
            get {
                return ResourceManager.GetString("FeatureGrialNavbarViewTitle", resourceCulture);
            }
        }
        
        internal static string FeatureGrialNavbarViewDescription {
            get {
                return ResourceManager.GetString("FeatureGrialNavbarViewDescription", resourceCulture);
            }
        }
        
        internal static string FeatureCheckboxesAndRadiosTitle {
            get {
                return ResourceManager.GetString("FeatureCheckboxesAndRadiosTitle", resourceCulture);
            }
        }
        
        internal static string FeatureCheckboxesAndRadiosDescription {
            get {
                return ResourceManager.GetString("FeatureCheckboxesAndRadiosDescription", resourceCulture);
            }
        }
        
        internal static string FeatureTabControlTitle {
            get {
                return ResourceManager.GetString("FeatureTabControlTitle", resourceCulture);
            }
        }
        
        internal static string FeatureTabControlDescription {
            get {
                return ResourceManager.GetString("FeatureTabControlDescription", resourceCulture);
            }
        }
        
        internal static string FeatureRepeaterTitle {
            get {
                return ResourceManager.GetString("FeatureRepeaterTitle", resourceCulture);
            }
        }
        
        internal static string FeatureRepeaterDescription {
            get {
                return ResourceManager.GetString("FeatureRepeaterDescription", resourceCulture);
            }
        }
        
        internal static string FeatureWrapPanelTitle {
            get {
                return ResourceManager.GetString("FeatureWrapPanelTitle", resourceCulture);
            }
        }
        
        internal static string FeatureWrapPanelDescription {
            get {
                return ResourceManager.GetString("FeatureWrapPanelDescription", resourceCulture);
            }
        }
        
        internal static string FeatureGridViewTitle {
            get {
                return ResourceManager.GetString("FeatureGridViewTitle", resourceCulture);
            }
        }
        
        internal static string FeatureGridViewDescription {
            get {
                return ResourceManager.GetString("FeatureGridViewDescription", resourceCulture);
            }
        }
        
        internal static string FeatureIconsTitle {
            get {
                return ResourceManager.GetString("FeatureIconsTitle", resourceCulture);
            }
        }
        
        internal static string FeatureIconsDescription {
            get {
                return ResourceManager.GetString("FeatureIconsDescription", resourceCulture);
            }
        }
        
        internal static string FeatureGrialFlowsTitle {
            get {
                return ResourceManager.GetString("FeatureGrialFlowsTitle", resourceCulture);
            }
        }
        
        internal static string FeatureGrialFlowsDescription {
            get {
                return ResourceManager.GetString("FeatureGrialFlowsDescription", resourceCulture);
            }
        }
        
        internal static string FeatureSafeAreaEffectTitle {
            get {
                return ResourceManager.GetString("FeatureSafeAreaEffectTitle", resourceCulture);
            }
        }
        
        internal static string FeatureSafeAreaEffectDescription {
            get {
                return ResourceManager.GetString("FeatureSafeAreaEffectDescription", resourceCulture);
            }
        }
        
        internal static string FeatureCustomRenderersTitle {
            get {
                return ResourceManager.GetString("FeatureCustomRenderersTitle", resourceCulture);
            }
        }
        
        internal static string FeatureCustomRenderersDescription {
            get {
                return ResourceManager.GetString("FeatureCustomRenderersDescription", resourceCulture);
            }
        }
        
        internal static string FeatureResponsiveHelpersTitle {
            get {
                return ResourceManager.GetString("FeatureResponsiveHelpersTitle", resourceCulture);
            }
        }
        
        internal static string FeatureResponsiveHelpersDescription {
            get {
                return ResourceManager.GetString("FeatureResponsiveHelpersDescription", resourceCulture);
            }
        }
        
        internal static string FeatureChartsTitle {
            get {
                return ResourceManager.GetString("FeatureChartsTitle", resourceCulture);
            }
        }
        
        internal static string FeatureChartsDescription {
            get {
                return ResourceManager.GetString("FeatureChartsDescription", resourceCulture);
            }
        }
        
        internal static string FeatureAnimationLoopsTitle {
            get {
                return ResourceManager.GetString("FeatureAnimationLoopsTitle", resourceCulture);
            }
        }
        
        internal static string FeatureAnimationLoopsDescription {
            get {
                return ResourceManager.GetString("FeatureAnimationLoopsDescription", resourceCulture);
            }
        }
        
        internal static string FeaturePoweredBy {
            get {
                return ResourceManager.GetString("FeaturePoweredBy", resourceCulture);
            }
        }
        
        internal static string GrialAboutDescription {
            get {
                return ResourceManager.GetString("GrialAboutDescription", resourceCulture);
            }
        }
        
        internal static string GrialAboutMission {
            get {
                return ResourceManager.GetString("GrialAboutMission", resourceCulture);
            }
        }
        
        internal static string GrialAboutTeam {
            get {
                return ResourceManager.GetString("GrialAboutTeam", resourceCulture);
            }
        }
        
        internal static string GrialAboutFollowUs {
            get {
                return ResourceManager.GetString("GrialAboutFollowUs", resourceCulture);
            }
        }
        
        internal static string GrialAboutEagerToHear {
            get {
                return ResourceManager.GetString("GrialAboutEagerToHear", resourceCulture);
            }
        }
        
        internal static string GrialAboutSayHello {
            get {
                return ResourceManager.GetString("GrialAboutSayHello", resourceCulture);
            }
        }
        
        internal static string GrialAboutGrialUses {
            get {
                return ResourceManager.GetString("GrialAboutGrialUses", resourceCulture);
            }
        }
        
        internal static string GrialAboutGrialThirdParty {
            get {
                return ResourceManager.GetString("GrialAboutGrialThirdParty", resourceCulture);
            }
        }
        
        internal static string GrialAboutGrialPoweredBy {
            get {
                return ResourceManager.GetString("GrialAboutGrialPoweredBy", resourceCulture);
            }
        }
        
        internal static string GrialAboutGrialCommunity {
            get {
                return ResourceManager.GetString("GrialAboutGrialCommunity", resourceCulture);
            }
        }
        
        internal static string GrialAboutTestimonialMiguelDeIcaza {
            get {
                return ResourceManager.GetString("GrialAboutTestimonialMiguelDeIcaza", resourceCulture);
            }
        }
        
        internal static string GrialAboutTestimonialDavidOrtinau {
            get {
                return ResourceManager.GetString("GrialAboutTestimonialDavidOrtinau", resourceCulture);
            }
        }
        
        internal static string WhatsNewDescription1 {
            get {
                return ResourceManager.GetString("WhatsNewDescription1", resourceCulture);
            }
        }
        
        internal static string WhatsNewDescription2 {
            get {
                return ResourceManager.GetString("WhatsNewDescription2", resourceCulture);
            }
        }
        
        internal static string WhatsNewDescription3 {
            get {
                return ResourceManager.GetString("WhatsNewDescription3", resourceCulture);
            }
        }
        
        internal static string WhatsNewDescription4 {
            get {
                return ResourceManager.GetString("WhatsNewDescription4", resourceCulture);
            }
        }
        
        internal static string WhatsNewDescription5 {
            get {
                return ResourceManager.GetString("WhatsNewDescription5", resourceCulture);
            }
        }
        
        internal static string WhatsNewTitle1 {
            get {
                return ResourceManager.GetString("WhatsNewTitle1", resourceCulture);
            }
        }
        
        internal static string WhatsNewTitle2 {
            get {
                return ResourceManager.GetString("WhatsNewTitle2", resourceCulture);
            }
        }
        
        internal static string WhatsNewTitle3 {
            get {
                return ResourceManager.GetString("WhatsNewTitle3", resourceCulture);
            }
        }
        
        internal static string WhatsNewTitle4 {
            get {
                return ResourceManager.GetString("WhatsNewTitle4", resourceCulture);
            }
        }
        
        internal static string WhatsNewTitle5 {
            get {
                return ResourceManager.GetString("WhatsNewTitle5", resourceCulture);
            }
        }
        
        internal static string TermsAndConditionsURL {
            get {
                return ResourceManager.GetString("TermsAndConditionsURL", resourceCulture);
            }
        }
        
        internal static string StringPickYourTheme {
            get {
                return ResourceManager.GetString("StringPickYourTheme", resourceCulture);
            }
        }
        
        internal static string LightThemeDescription {
            get {
                return ResourceManager.GetString("LightThemeDescription", resourceCulture);
            }
        }
        
        internal static string DarkThemeDescription {
            get {
                return ResourceManager.GetString("DarkThemeDescription", resourceCulture);
            }
        }
        
        internal static string BlackboardThemeDescription {
            get {
                return ResourceManager.GetString("BlackboardThemeDescription", resourceCulture);
            }
        }
        
        internal static string BlackSunThemeDescription {
            get {
                return ResourceManager.GetString("BlackSunThemeDescription", resourceCulture);
            }
        }
        
        internal static string HazeThemeDescription {
            get {
                return ResourceManager.GetString("HazeThemeDescription", resourceCulture);
            }
        }
        
        internal static string CabernetLightThemeDescription {
            get {
                return ResourceManager.GetString("CabernetLightThemeDescription", resourceCulture);
            }
        }
    }
}
